import type { IDataObject, IExecuteFunctions, INodeProperties } from 'n8n-workflow';
import { generateSignature } from '../client/checksum';
import { PAYTM_API_CREDENTIAL_NAME } from '../constants';
import { Operation } from '../enums';
import type {
	FetchPaymentLinksBody,
	FetchPaymentLinksSearchFilter,
	PaytmChecksumApiResponse,
} from '../types';
import { getBody, resolvePaytmSecureApiUrl } from '../utils/credentialUtil';
import { responseValidation } from '../utils/responseValidationUtil';
import { toDdMmYyyySlashIstFromNodeValue } from '../utils/dateParamUtils';

const FETCH_PAYMENT_LINKS_SHOW = { show: { operation: [Operation.FETCH_PAYMENT_LINKS] } };

function trimStr(v: unknown): string {
	if (v === undefined || v === null) return '';
	return String(v).trim();
}

/** Optional `/link/fetch` filters — shown only after Add Field (same pattern as Create Payment Link). */
const FETCH_PAYMENT_LINKS_ADDITIONAL_OPTIONS: INodeProperties[] = [
	{
		displayName: 'Customer Details',
		name: 'customerDetails',
		type: 'collection',
		placeholder: 'Add Customer Details',
		default: {},
		options: [
			{
				displayName: 'Customer Email',
				name: 'customerEmail',
				type: 'string',
				default: '',
				placeholder: 'customer@example.com',
				description: 'Fetch links using customer email address',
			},
			{
				displayName: 'Customer Mobile',
				name: 'customerMobile',
				type: 'string',
				default: '',
				placeholder: '9876543210',
				description: 'Fetch links using customer phone number',
			},
			{
				displayName: 'Customer Name',
				name: 'customerName',
				type: 'string',
				default: '',
				placeholder: 'John Doe',
				description: 'Fetch links using customer name',
			},
		],
	},
	{
		displayName: 'Link ID',
		name: 'linkId',
		type: 'string',
		default: '',
		placeholder: '123456789',
		description: 'Unique identifier for each link',
	},
	{
		displayName: 'Link Type',
		name: 'linkTypeMultiple',
		type: 'multiOptions',
		options: [
			{ name: 'Fixed', value: 'FIXED' },
			{ name: 'Generic', value: 'GENERIC' },
		],
		default: [],
		description: 'Link type to fetch',
	},
	{
		displayName: 'Merchant Request ID',
		name: 'merchantRequestId',
		type: 'string',
		default: '',
		placeholder: 'unique-request-ID',
		description: 'Unique ID generated by merchant',
	},
	{
		displayName: 'Payment Status',
		name: 'paymentStatus',
		type: 'options',
		default: 'PENDING',
		options: [
			{ name: 'Expired', value: 'EXPIRED' },
			{ name: 'Init', value: 'INIT' },
			{ name: 'Paid', value: 'PAID' },
			{ name: 'Pending', value: 'PENDING' },
		],
		description: 'Fetch links based on payment status',
	},
	{
		displayName: 'Reseller ID',
		name: 'resellerId',
		type: 'string',
		default: '',
		placeholder: 'reseller reference',
		description: 'Fetch links based on reseller ID',
	},
	{
		displayName: 'Reseller Name',
		name: 'resellerName',
		type: 'string',
		default: '',
		placeholder: 'reseller name',
		description: 'Fetch links based on reseller name',
	},
	{
		displayName: 'Search Filter Request Body',
		name: 'searchFilterRequestBody',
		type: 'collection',
		placeholder: 'Add Search Filter Field',
		default: {},
		description:
			'Add From Date, To Date, and/or Link Active Status. Dates are sent to Paytm as DD/MM/YYYY or DD/MM/YYYY HH:MM:SS (IST).',
		options: [
			{
				displayName: 'From Date',
				name: 'fromDate',
				type: 'dateTime',
				default: '',
				description: 'Start date to fetch payment links',
			},
			{
				displayName: 'Link Active Status',
				name: 'isActive',
				type: 'options',
				default: '',
				options: [
					{ name: 'Any', value: '' },
					{ name: 'Active Only', value: 'true' },
					{ name: 'Inactive Only', value: 'false' },
				],
			},
			{
				displayName: 'To Date',
				name: 'toDate',
				type: 'dateTime',
				default: '',
				description: 'End date to fetch payment links',
			},
		],
	},
];

export const fetchPaymentLinksDescription: INodeProperties[] = [
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: FETCH_PAYMENT_LINKS_SHOW,
		options: FETCH_PAYMENT_LINKS_ADDITIONAL_OPTIONS,
	},
];

function parseLinkIdForBody(raw: string): number | string | undefined {
	const t = raw.trim();
	if (!t) return undefined;
	const n = Number(t);
	if (!Number.isNaN(n) && Number.isFinite(n) && String(n) === t) {
		return n;
	}
	return t;
}

/** Maps nested collection output (flat keys like Customer Details) to API `searchFilterRequestBody`. */
function buildSearchFilter(raw: IDataObject): FetchPaymentLinksSearchFilter | undefined {
	if (!raw || Object.keys(raw).length === 0) return undefined;

	/** Older node versions used `fixedCollection` with `filter: [{ ... }]`. */
	const legacyRows = raw.filter as Array<IDataObject> | undefined;
	const row =
		Array.isArray(legacyRows) && legacyRows.length > 0 && legacyRows[0]
			? (legacyRows[0] as IDataObject)
			: raw;

	const fromDateRaw = toDdMmYyyySlashIstFromNodeValue(row.fromDate);
	const toDateRaw = toDdMmYyyySlashIstFromNodeValue(row.toDate);
	const fromDate = fromDateRaw.trim() || undefined;
	const toDate = toDateRaw.trim() || undefined;

	const activeRaw = row.isActive;
	let isActive: boolean | undefined;
	if (activeRaw === true || activeRaw === 'true') {
		isActive = true;
	} else if (activeRaw === false || activeRaw === 'false') {
		isActive = false;
	}

	if (!fromDate && !toDate && isActive === undefined) {
		return undefined;
	}

	const out: FetchPaymentLinksSearchFilter = {};
	if (fromDate) out.fromDate = fromDate;
	if (toDate) out.toDate = toDate;
	if (isActive !== undefined) out.isActive = isActive;
	return Object.keys(out).length > 0 ? out : undefined;
}

/** Inner `/link/fetch` `body` from node parameters (checksum `body` only). */
function buildFetchPaymentLinksBody(
	context: IExecuteFunctions,
	itemIndex: number,
	mid: string,
): FetchPaymentLinksBody {
	const body: FetchPaymentLinksBody = { mid };

	const additionalRaw = context.getNodeParameter('additionalFields', itemIndex, {}) as IDataObject;

	const merchantRequestId = trimStr(additionalRaw.merchantRequestId);
	if (merchantRequestId) body.merchantRequestId = merchantRequestId;

	const linkIdStr = trimStr(additionalRaw.linkId);
	const linkIdParsed = parseLinkIdForBody(linkIdStr);
	if (linkIdParsed !== undefined) {
		body.linkId = linkIdParsed;
	}

	const searchFilterPack = (additionalRaw.searchFilterRequestBody as IDataObject | undefined) ?? {};
	const searchFilter = buildSearchFilter(searchFilterPack);
	if (searchFilter) {
		body.searchFilterRequestBody = searchFilter;
	}

	const linkTypes = additionalRaw.linkTypeMultiple as string[] | undefined;
	if (Array.isArray(linkTypes) && linkTypes.length > 0) {
		body.linkTypeMultiple = [...linkTypes];
	}

	const detailPack = (additionalRaw.customerDetails as IDataObject | undefined) ?? {};
	const customerName = trimStr(detailPack.customerName ?? additionalRaw.customerName);
	if (customerName) body.customerName = customerName;

	const customerPhone = trimStr(detailPack.customerMobile ?? additionalRaw.customerPhone);
	if (customerPhone) body.customerPhone = customerPhone;

	const customerEmail = trimStr(detailPack.customerEmail ?? additionalRaw.customerEmail);
	if (customerEmail) body.customerEmail = customerEmail;

	const paymentStatus = trimStr(additionalRaw.paymentStatus);
	if (paymentStatus) {
		body.paymentStatus = paymentStatus;
	}

	const resellerId = trimStr(additionalRaw.resellerId);
	if (resellerId) body.resellerId = resellerId;

	const resellerName = trimStr(additionalRaw.resellerName);
	if (resellerName) body.resellerName = resellerName;

	return body;
}

/** Assembles Paytm checksum envelope `{ body, head }` for `/link/fetch`. */
function buildFetchPaymentLinksPayload(
	innerBody: FetchPaymentLinksBody,
	signature: string,
): Record<string, unknown> {
	return {
		body: innerBody,
		head: {
			tokenType: 'AES',
			signature,
			channelId: 'WEB',
		},
	};
}

export async function executeFetchPaymentLinks(
	this: IExecuteFunctions,
	itemIndex: number,
): Promise<unknown> {
	const creds = await this.getCredentials(PAYTM_API_CREDENTIAL_NAME);
	const mid = creds.merchantId as string;
	const keySecret = String(creds.keySecret ?? '').trim();

	const innerBody = buildFetchPaymentLinksBody(this, itemIndex, mid);
	const signature = await generateSignature(innerBody, keySecret);
	const payload = buildFetchPaymentLinksPayload(innerBody, signature);

	const res = (await this.helpers.httpRequestWithAuthentication.call(this, PAYTM_API_CREDENTIAL_NAME, {
		method: 'POST',
		url: resolvePaytmSecureApiUrl(creds.environment as string | undefined, 'PAYMENT_LINK_FETCH'),
		body: payload,
		json: true,
	})) as PaytmChecksumApiResponse;
	responseValidation(res);
	return getBody(res) ?? res;
}
